apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-pipeline-run-
spec:
  pipelineRef:
    name: hello-pipeline

  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: hello-pvc
  # serviceAccountName: build-bot
