apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: adjust-sha-image-generated
  # namespace: hello # Certifique-se de usar o namespace correto
  labels:
    app.kubernetes.io/version: "0.9"
spec:
  description: >
    Ajusta o SHA-DIGEST gerado na etapa anterior.

  params:
    - name: IMAGE_DIGEST
      description: "SHA-DIGEST da imagem gerado na etapa anterior."
      type: string

  workspaces:
    - name: source
      description: "Workspace contendo o código-fonte"

  results:
    - name: DIGEST
      description: "SHA-DIGEST da imagem ajustado."

  steps:
    - name: adjust
      image: ubuntu
      workingDir: $(workspaces.source.path)
      env:
        - name: PARAM_DIGEST
          value: $(params.IMAGE_DIGEST)
      script: |
        #!/bin/bash
        set -e

        # Remover espaços em branco e quebras de linha
        DIGEST=$(echo "$(params.IMAGE_DIGEST)" | tr -d '[:space:]' | cut -d':' -f2)

        # Garantir que o digest não esteja vazio
        if [ -z "$DIGEST" ]; then
          echo "Error: DIGEST is empty!"
          exit 1
        fi

        printf '%s' "${DIGEST}" | tee "$(results.DIGEST.path)"
