apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml

namespace: hello

images:
- name: marcelobruckner/hello
  newName: marcelobruckner/hello
  newTag: 6e21192591e69661553a78a9d673cd8d0dc400ef
