apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service.yaml
  - deployment.yaml
  - route.yaml

namespace: hello

images:
  - name: default-route-openshift-image-registry.apps-crc.testing/hello/hello
    newName: default-route-openshift-image-registry.apps-crc.testing/hello/hello
    newTag: a111a1923fb1bf68670ec71e7cb53f7f492bd3740d4b5b16fa06c140454e6f01
