apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- route.yaml

namespace: hello

images:
- name: marcelobruckner/hello
  newName: marcelobruckner/hello
  newTag: de30e19d0f257389e5d7249a65708fb66132708d2252a3ee2fdc217fd12e3ae1
