apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- route.yaml

namespace: hello

images:
- name: default-route-openshift-image-registry.apps-crc.testing/hello/hello
  newName: default-route-openshift-image-registry.apps-crc.testing/hello/hello
  newTag: 526e5b6b62559ed6ee5a3dc64528e482f3026e24a5c3b08125278938ad192f23
- name: image-registry.openshift-image-registry.svc:5000/hello/hello
  newName: image-registry.openshift-image-registry.svc:5000/hello/hello
  newTag: 2c92e259fdb1ce3441e39687839cfd8b4840d85bad7133377e04d3b0617f6a79
