apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- route.yaml

namespace: hello

images:
- name: image-registry.openshift-image-registry.svc:5000/hello/hello
  newName: image-registry.openshift-image-registry.svc:5000/hello/hello
  newTag: 84a8e2340bd91529daabceeea4609bb7d9d0724086922d7020014cb2b795f228
