apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- route.yaml

namespace: hello

images:
- name: marcelobruckner/hello
  newName: marcelobruckner/hello
  newTag: d44d2da29e745f04d8e3d0b952bea2f68e8f7f236d8ab9fbfd0e7e6cb6e7d5b4
