apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml

namespace: hello

images:
- name: marcelobruckner/hello
  newName: marcelobruckner/hello
  newTag: d92a42e63b43cc06ed47d4183a456fdc7f4616d7
