apiVersion: v1
items:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      labels:
        app: hello
        app.kubernetes.io/instance: hello
      name: hello
      namespace: hello
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: hello
    status:
      ingress:
        - conditions:
            - lastTransitionTime: "2025-03-28T18:37:42Z"
              status: "True"
              type: Admitted
          host: hello-hello.apps-crc.testing
          routerCanonicalHostname: router-default.apps-crc.testing
          routerName: default
          wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
