apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  # namespace: hello # Certifique-se de usar o namespace correto
  annotations:
    tekton.dev/service-account: "true" # Adiciona uma anotação para facilitar o rastreamento de sua origem
secrets:
  # - name: dockerhub-secret # Secret com credenciais do Docker Hub para autenticação
  - name: github-secret # Secret com credenciais do GitHub para acesso ao repositório
  - name: internal-registry-secret
imagePullSecrets:
  - name: internal-registry-secret
# - name: dockerhub-secret # Secret com credenciais do Docker Hub para pull de imagens
# - name: github-secret # Secret com credenciais do GitHub para pull de imagens
