apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: hello # Certifique-se de usar o namespace correto
  annotations:
    tekton.dev/service-account: "true" # Adiciona uma anotação para facilitar o rastreamento de sua origem
secrets:
  - name: dockerhub-secret # Secret com credenciais do Docker Hub para autenticação
  - name: github-secret # Secret com credenciais do GitHub para acesso ao repositório

# Você pode adicionar um RoleBinding ou ClusterRoleBinding, dependendo das permissões necessárias
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: build-bot-role-binding
#   namespace: hello # Certifique-se de usar o namespace correto
# subjects:
#   - kind: ServiceAccount
#     name: build-bot
#     namespace: hello # Certifique-se de usar o namespace correto
# roleRef:
#   kind: Role
#   name: secret-reader # A role pode ser 'secret-reader' ou outra role que tenha permissão de leitura de Secrets
#   apiGroup: rbac.authorization.k8s.io
