apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: adjust-sha-image-generated-run
spec:
  taskRef:
    name: adjust-sha-image-generated
  params:
    - name: IMAGE_DIGEST
      value: "sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: hello-pvc
